ingress:
  # allows you to specify custom hosts
  customHosts:
    # specify your ngrok custom domain here
    # such as
    #    hook: "myuniqueid.ngrok.io
    # so that webhooks from, say, github.com, will work to your local laptop
    hook: "f906-2800-40-33-44ea-e5b1-5370-3fb9-16c9.sa.ngrok.io"

kaniko:
  # lets support insecure docker registries so that we
  # can use the local docker-registry chart
  flags: "--insecure"
